version: '3.8'

services:
  app:
    image: swathip2003/springApplication1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9097:9097"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/springApplication
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: springApplication
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
